name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened] # Same as default

permissions:
  contents: read
  pull-requests: write

jobs:
  paths:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      action: ${{ steps.filter.outputs.action }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            action:
              - ".github/**"

  action:
    name: Action files
    needs: paths
    if: ${{ needs.paths.outputs.action == 'true' || github.event_name == 'push'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true
